name: eznit

services:
  db:
    image: postgres:18
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ./db/migrations/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 10

  migrate:
    image: migrate/migrate:latest
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PWD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable",
        "up",
      ]
    volumes:
      - ./db/migrations:/migrations:ro
    depends_on:
      db:
        condition: service_healthy

  api:
    image: alpine:3.23
    env_file:
      - path: .env
        required: true
    command: ./api/server
    ports:
      - "${API_PORT}:4000"
    volumes:
      - ./build/linux/api/server:/api/server:ro
    depends_on:
      - migrate

volumes:
  postgres-data:
